from .dir import CONFUSING_DIRS
from .reserved_word import SPECIAL_RULES_RESERVED_WORDS

LINENO_PADDING_WIDTH = 7

__all__ = ["CONFUSING_DIRS", "SPECIAL_RULES_RESERVED_WORDS", "LINENO_PADDING_WIDTH"]
